source 'https://rubygems.org'
ruby '3.3.1'

gem 'byebug'
gem 'capybara'
gem 'capybara-screenshot'
gem 'chilkat'
gem 'chunky_png', '1.3.7'
gem 'cucumber', '3.2.0'
gem 'cuke_sniffer'
gem 'date'
gem 'dotenv'
gem 'imatcher', '0.1.5'
gem 'new_data_magic', '~> 1.2'
gem 'os'
gem 'parallel_tests'
gem 'pdf-reader'
gem 'pry'
gem 'pry-byebug'
gem 'rake'
gem 'report_builder'
gem 'require_all'
gem 'roo'
gem 'roo-xls'
gem 'rspec'
gem 'rspec-expectations'
gem 'rubocop', '1.48.1', require: false
gem 'selenium-webdriver', '~> 4.16.0'
gem 'show_me_the_cookies'
gem 'simple_xlsx_reader'
gem 'site_prism', '~> 3.7.3'
gem 'site_prism-table'
gem 'sorted_set'
gem 'syntax'
gem 'sorted_set'
